/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.List;

import static java.util.Collections.emptyList;

public class PrimeFactors {

    public List<Integer> of(int number) {
       List<Integer> list=emptyList();

       if(number==1)
           return list;
       //else write code to add the prime factors to the list.
       return list;

    }
}
